import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";

import { ThemeProvider } from "@/providers/theme-provider";
import "./globals.css";

const josefin = Josefin_Sans({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="vi" className={josefin.className}>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{/* put header here */}
					<div className={`w-[80%] mx-auto`}>{children}</div>
					{/* put footer here */}
				</ThemeProvider>
			</body>
		</html>
	);
}
